# -*- coding: utf-8 -*-
"""Chapter 8: - Multiple Linear Regression colab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awlijGw6JtyKfMgtT-9nraKia5uOyIVg

# 1. Linear Regression

1. Importing the Libraries
"""

# Importing the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""2. Data Acquistion"""

#Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')
URL_GD = '/content/drive/MyDrive/CHapter ML/50_AdAgency.csv'
dataset = pd.read_csv(URL_GD)

"""3.  Creating Data Frames

"""

# Creating Data Frames
X = dataset.iloc[:, :- 1].values
Y = dataset.iloc[:, 4].values

"""4. Encoding categorical data"""

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder = LabelEncoder()
X[:,3] = labelencoder.fit_transform(X[:,3])

ct = ColumnTransformer([("City", OneHotEncoder(), [3])], 							remainder = 'passthrough')
X = ct.fit_transform(X)

"""5. Avoiding the Dummy Variable Trap"""

# Avoiding the Dummy Variable Trap
X = X[:, 1:]

"""6. Dataset Splition"""

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size= 0.2, random_state = 0)

"""7. Modeling"""

from sklearn.linear_model import LinearRegression
linear_regressor = LinearRegression()
linear_regressor.fit(X_train, Y_train)

"""8. Predictions"""

# Predicting the Test set results
Y_pred = linear_regressor.predict(X_test)

"""9. Performance Evaluation

"""

# Importing metrics library
from sklearn import metrics
# Evaluating the model and printing the results using MAE
print(metrics.mean_absolute_error(Y_test, Y_pred))

# Evaluating the model and printing the results using MSE
print(metrics.mean_squared_error(Y_test, Y_pred))

# Importing the math library
import math

# Evaluating the model and printing the results using RMSE
print(np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

"""#**Polynomial Regression**

2.1: Importing of the Libraries
"""

# Polynomial Regression

# Importing the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""2.2: Data Acquistion"""

#Mounting Google Drive
URL_GD = '/content/drive/MyDrive/CHapter ML/Position_Salaries.csv'
dataset = pd.read_csv(URL_GD)

"""2.3:  Creating Data Frames

"""

# Creating Data Frames
X = dataset.iloc[:, 1:2].values
Y = dataset.iloc[:, 2].values

"""2.4: Creating Polynomial Regressor"""

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X)

"""2.5: Training the Polynomial Regression model on the whole dataset

"""

#Training the Polynomial Regression model on the whole dataset
from sklearn.linear_model import LinearRegression
Poly_reg_model = LinearRegression()
Poly_reg_model.fit(X_poly, Y)

"""2.6: Visualising the Training set results"""

# Visualising the Training set results
plt.scatter(X, Y, color = 'red')
plt.title('Visualization of Training Data')
plt.xlabel('Years of Research Experience')
plt.ylabel('Stipend')
plt.plot(X, Poly_reg_model.predict(X_poly), color = 'blue')

"""2.7:  Changing the degree of polynomial to 3 """

#Transforming X to higher degree polynomial terms
from sklearn.preprocessing import PolynomialFeatures
Poly_reg = PolynomialFeatures(degree = 3)
X_poly = Poly_reg.fit_transform(X)
 
#Training the Polynomial Regression model on the whole dataset
from sklearn.linear_model import LinearRegression
Poly_reg_model = LinearRegression()
Poly_reg_model.fit(X_poly, Y)

# Visualising the Polynomial Regression results
plt.scatter(X,Y, color = 'red') 
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.plot(X, Poly_reg_model.predict(X_poly), color = 'blue')

"""2.8: Changing the degree of polynomial to 4"""

#Transforming X to higher degree polynomial terms
from sklearn.preprocessing import PolynomialFeatures
Poly_reg = PolynomialFeatures(degree = 4)
X_poly = Poly_reg.fit_transform(X)
 
#Training the Polynomial Regression model on the whole dataset
from sklearn.linear_model import LinearRegression
Poly_reg_model = LinearRegression()
Poly_reg_model.fit(X_poly, Y)

# Visualising the Polynomial Regression results
plt.scatter(X,y, color = 'red') 
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.plot(X, Poly_reg_model.predict(X_poly), color = 'blue')

"""2.9: Predict Polynomial Regression Results"""

Poly_reg_model.predict(Poly_reg.fit_transform([[7.5]]))

"""2.10: Comparison of Linear Regression and Polynomial Regression Results"""

#Comparison of Linear Regression and Polynomial Regression Results
from sklearn.linear_model import LinearRegression
# Training the Linear Regression model on the whole dataset
linear_regressor = LinearRegression()
linear_regressor.fit(X, Y)

"""2.11: Visualising the Polynomial Regression results"""

# Visualising the Polynomial Regression results
plt.scatter(X, Y, color = 'red') 
plt.plot(X, linear_regressor.predict(X), color = 'blue')
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()

"""# **3. Case study of Chemistry students**"""

# Polynomial Regression – Chemistry Student Problem
#Importing the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#Importing the Libraries
Dataset = pd.read_csv('/content/drive/MyDrive/CHapter ML/Chemistry_Problem.csv')  
X = Dataset.iloc[:, 1: 2].values
Y = Dataset.iloc[:, 2].values  
#Transforming X to higher degree polynomial terms 
from sklearn.preprocessing import PolynomialFeatures
Poly_reg = PolynomialFeatures(degree = 2)
X_poly = Poly_reg.fit_transform(X)

#Training the Polynomial Regression model on the whole dataset
from sklearn.preprocessing import PolynomialFeatures
Poly_reg_model = LinearRegression()
Poly_reg_model.fit(X_poly, Y) 

# Visualising the Polynomial Regression results
plt.scatter(X, Y, color = 'red')  
plt.plot(X, Poly_reg_model.predict(X_poly), color = 'blue')
plt.xlabel('Temperature')
plt.ylabel('Pressure')
plt.show()

# Training the Linear Regression model on the whole dataset
linear_regressor = LinearRegression()
linear_regressor.fit(X, Y) 

# Visualizing the Polynomial Regression results
plt.scatter(X, Y, color = 'red') 
plt.plot(X, linear_regressor.predict(X), color = 'blue')
plt.xlabel('Temperature')
plt.ylabel('Pressure')
plt.show() 

# Predicting a new result with Linear Regression
linear_regressor.predict([[30]])